#!/bin/sh
#
# Build a .deb for Debian 13 (trixie) and derivatives.
#
# The package depends on Debian's own PySide6 rather than bundling Qt. That
# is the whole reason to ship a .deb at all: on the distribution this app was
# built for, Qt is already there, already patched, and already matches the
# desktop the user is running. Bundling it would add 400 MB to duplicate what
# is installed.
#
# Architecture: all. The only native code is libasound, reached through
# ctypes at run time, so there is nothing here to compile.
#
# Usage: packaging/build-deb.sh [output-directory]
#
set -eu

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
out=${1:-$root/dist}

version=$(sed -n 's/^__version__ = "\(.*\)"/\1/p' "$root/lmssdr/__init__.py")
[ -n "$version" ] || { echo "error: no version in lmssdr/__init__.py" >&2; exit 1; }

pkg=lmssdr
stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT
root_dir="$stage/$pkg"

echo "Building $pkg $version"

# -- the payload ----------------------------------------------------------

site=$root_dir/usr/lib/python3/dist-packages
install -d "$site/$pkg"
# The package itself, without the test suite, the build metadata or any
# stray bytecode from a development checkout.
(cd "$root" && find "$pkg" -type f \
    \( -name '*.py' -o -name '*.qml' -o -name '*.png' \) -print) |
while read -r file; do
    install -D -m 0644 "$root/$file" "$site/$file"
done

install -d "$root_dir/usr/bin"
cat > "$root_dir/usr/bin/lmssdr" <<'EOF'
#!/usr/bin/python3
# Generated by packaging/build-deb.sh. The console script setuptools would
# normally write is not used, because the .deb installs the package into
# dist-packages by hand rather than through pip.
import sys

from lmssdr.app import main

sys.exit(main())
EOF
chmod 0755 "$root_dir/usr/bin/lmssdr"

# -- the privileged helper ------------------------------------------------

install -D -m 0755 "$here/polkit/lmssdr-module-helper" \
    "$root_dir/usr/libexec/lmssdr/lmssdr-module-helper"
install -D -m 0644 "$here/polkit/org.atmanactive.lmssdr.policy" \
    "$root_dir/usr/share/polkit-1/actions/org.atmanactive.lmssdr.policy"

# -- desktop integration --------------------------------------------------

install -D -m 0644 "$here/lmssdr.desktop" \
    "$root_dir/usr/share/applications/lmssdr.desktop"

[ -d "$here/icons" ] || { echo "error: run packaging/make-icons.py first" >&2; exit 1; }
for dir in "$here"/icons/*x*; do
    size=$(basename "$dir")
    for icon in "$dir"/*.png; do
        install -D -m 0644 "$icon" \
            "$root_dir/usr/share/icons/hicolor/$size/apps/$(basename "$icon")"
    done
done

# -- documentation --------------------------------------------------------

doc=$root_dir/usr/share/doc/$pkg
install -D -m 0644 "$root/README.md" "$doc/README.md"
install -D -m 0644 "$root/LICENSE" "$doc/copyright"
printf '%s (%s) unstable; urgency=low\n\n  * See %s/releases\n\n -- %s  %s\n' \
    "$pkg" "$version" \
    "https://github.com/AtmanActive/Linux-MIDI-snd_seq_dummy-Router" \
    "AtmanActive <atmanactive@gmail.com>" "$(date -R)" \
    | gzip -9n > "$doc/changelog.Debian.gz"
chmod 0644 "$doc/changelog.Debian.gz"

# -- control --------------------------------------------------------------

# Installed-Size is in KiB and is what apt shows before installing.
size=$(du -ks "$root_dir" | cut -f1)

install -d "$root_dir/DEBIAN"
cat > "$root_dir/DEBIAN/control" <<EOF
Package: $pkg
Version: $version
Section: sound
Priority: optional
Architecture: all
Maintainer: AtmanActive <atmanactive@gmail.com>
Installed-Size: $size
Depends: python3 (>= 3.11),
 python3-pyside6.qtcore,
 python3-pyside6.qtgui,
 python3-pyside6.qtwidgets,
 python3-pyside6.qtqml,
 python3-pyside6.qtquick,
 qml6-module-qtquick,
 qml6-module-qtquick-controls,
 qml6-module-qtquick-layouts,
 qml6-module-qtquick-dialogs,
 libasound2t64 | libasound2,
 pkexec | policykit-1
Recommends: pulseaudio-utils
Homepage: https://github.com/AtmanActive/Linux-MIDI-snd_seq_dummy-Router
Description: Control and route ALSA snd_seq_dummy MIDI ports
 A desktop application that owns ALSA's snd_seq_dummy MIDI ports: how many
 there are, what you call them, and how they are wired to each other.
 .
 snd_seq_dummy is the only MIDI port source that Chromium's Web MIDI and
 DAWs such as Reaper both see, because both ignore sequencer clients with an
 id of 16 or above. On its own it offers a fixed port count chosen at module
 load and names hardcoded to "Midi Through Port-N". This application adds a
 settable port count, per-port aliases, remarks and colours, a routing matrix
 that creates real ALSA subscriptions, and a microphone mute driven by Mackie
 transport messages from a DAW.
 .
 Built for KDE Plasma on Wayland.
EOF

# pulseaudio-utils is a Recommends, not a Depends: everything except the
# microphone mute works without it, and a system with no PulseAudio or
# PipeWire should still be able to install the router.

cat > "$root_dir/DEBIAN/postinst" <<'EOF'
#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor 2>/dev/null || true
    fi
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications 2>/dev/null || true
    fi
fi
exit 0
EOF
chmod 0755 "$root_dir/DEBIAN/postinst"

cat > "$root_dir/DEBIAN/postrm" <<'EOF'
#!/bin/sh
set -e
# The module configuration is written as root by the polkit helper, not by
# dpkg, so dpkg will not remove it. Purging should: leaving it behind means a
# port count set by an application that is no longer installed still wins at
# the next boot.
if [ "$1" = "purge" ]; then
    rm -f /etc/modprobe.d/lmssdr.conf
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor 2>/dev/null || true
    fi
fi
exit 0
EOF
chmod 0755 "$root_dir/DEBIAN/postrm"

# -- build ----------------------------------------------------------------

mkdir -p "$out"
deb="$out/${pkg}_${version}_all.deb"
# --root-owner-group so the package does not carry the build user's uid,
# which is what fakeroot would otherwise be needed for.
dpkg-deb --root-owner-group -Zxz --build "$root_dir" "$deb" >/dev/null

echo "Built $deb"
